# The API URL
ipfs-api-url = "127.0.0.1"

# The API Port
ipfs-api-port = 5001

# Whether to automatically "ipfs pin" chain objects
autoserve-chains = true

# Whether to automatically "ipfs pin" foreign posts if their content is text
autoserve-text-posts = true

# Whether to serve content/chains from blocked profiles
serve-blocked = false

# Whether to automatically "ipfs pin" followed profiles
autoserve-followed = true

# Default amount of bytes which are loaded for each post
max-autoload-per-post = 1024

# List of Mimetypes which should not be served
autoserve-blacklist = []

# List of Mimetypes which can be served
autoserve-whitelist = []

